//import './tipos/variaveis'
//import './tipos/array'
//import './tipos/enums'
//import './tipos/enums_const'

//import './tipos/erros'
//import './tipos/enums_tipo'
//import './tipos/funcoes'
//import './tipos/objetos'
//import './tipos/produto'
//import './tipos/uniao'
//import './tipos/never'
import './tipos/null'
